/** File I/O shared by the i18n scripts (sync-i18n-keys, translate-i18n). See docs/I18N.md. */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import coverage from "./i18nCoverage.js";

const { sortObject, serializeStatus } = coverage;

export const appDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
export const i18nDir = path.join(appDir, "lib", "i18n");
export const localesDir = path.join(i18nDir, "locales");
export const patchesDir = path.join(i18nDir, "patches");
export const statusPath = path.join(i18nDir, "translation-status.json");

export const STATUS_README =
  "Generated by `npm run sync-i18n` / `npm run translate-i18n` — do not edit by hand. Per locale and key: " +
  '{ status: "needs_translation", en_hash } = English placeholder; ' +
  '{ status: "translated", method: machine|human|legacy, reviewed, date, en_hash } = translation of the English with that hash ' +
  "(a different hash means the English changed and the key gets retranslated). See docs/I18N.md.";

export const readJson = (p) => JSON.parse(fs.readFileSync(p, "utf8"));

export const loadConfig = () => readJson(path.join(i18nDir, "coverage-config.json"));
export const loadGlossary = () => readJson(path.join(i18nDir, "glossary.json"));
export const loadEn = () => readJson(path.join(localesDir, "en.json"));
export const loadStatus = () => (fs.existsSync(statusPath) ? readJson(statusPath) : {});

/** Locale codes with a file in locales/, English excluded, sorted. */
export function listLocales() {
  return fs
    .readdirSync(localesDir)
    .filter((f) => f.endsWith(".json") && f !== "en.json" && !f.startsWith("_"))
    .map((f) => f.replace(".json", ""))
    .sort();
}

export const loadLocale = (locale) => readJson(path.join(localesDir, `${locale}.json`));

export function writeLocale(locale, loc) {
  fs.writeFileSync(path.join(localesDir, `${locale}.json`), `${JSON.stringify(sortObject(loc), null, 2)}\n`, "utf8");
}

/** Writes translation-status.json; returns true when the content changed. */
export function writeStatus(status) {
  const serialized = serializeStatus(status, STATUS_README);
  const changed = !fs.existsSync(statusPath) || fs.readFileSync(statusPath, "utf8") !== serialized;
  if (changed) fs.writeFileSync(statusPath, serialized, "utf8");
  return changed;
}

/** Merge all patch files in lib/i18n/patches/ (locale → key → translation). */
export function loadMergedPatches() {
  const merged = {};
  if (!fs.existsSync(patchesDir)) return merged;
  for (const file of fs.readdirSync(patchesDir).filter((f) => f.endsWith(".json"))) {
    const data = readJson(path.join(patchesDir, file));
    for (const [locale, keys] of Object.entries(data)) {
      merged[locale] = { ...(merged[locale] ?? {}), ...keys };
    }
  }
  return merged;
}

/** Minimal KEY=VALUE loader for apps/mobile/.env.translate (git-ignored); never overrides the shell. */
export function loadEnvFile(file = path.join(appDir, ".env.translate")) {
  if (!fs.existsSync(file)) return;
  for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*(?:export\s+)?([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (!m || line.trim().startsWith("#")) continue;
    const value = m[2].replace(/^(['"])(.*)\1$/, "$2");
    if (process.env[m[1]] === undefined) process.env[m[1]] = value;
  }
}
