-- ─────────────────────────────────────────────────────────────────────────────
-- Schema drift check — run in the SQL Editor of ANY environment (dev or prod).
--
-- Why this exists: 20250130000001_winkly_schema.sql creates all 20 base tables
-- with CREATE TABLE IF NOT EXISTS. That file has been edited after it was first
-- applied. Supabase tracks migrations by version, so an edited file never re-runs,
-- and IF NOT EXISTS means the table is left exactly as it was — silently missing
-- any column added to the file later.
--
-- This is a known, recurring problem in this project: 20260630120000_weekly_spark_core.sql
-- line 183 already patches users.status for the same reason. users.premium_until was
-- the same bug, undetected because nothing crashed — the AI tier just silently
-- degraded every user to 'free'.
--
-- Read-only. Returns zero rows when the environment matches the base schema.
-- ─────────────────────────────────────────────────────────────────────────────

with expected(table_name, column_name) as (values
  ('users','id'),
  ('users','email'),
  ('users','account_type'),
  ('users','is_premium'),
  ('users','premium_until'),
  ('users','status'),
  ('users','created_at'),
  ('users','updated_at'),
  ('profiles_core','id'),
  ('profiles_core','first_name'),
  ('profiles_core','last_name'),
  ('profiles_core','gender'),
  ('profiles_core','birthday'),
  ('profiles_core','city'),
  ('profiles_core','education'),
  ('profiles_core','languages'),
  ('profiles_core','occupation'),
  ('profiles_core','bio'),
  ('profiles_core','core_photos'),
  ('profiles_core','created_at'),
  ('profiles_core','updated_at'),
  ('profiles_mode','id'),
  ('profiles_mode','user_id'),
  ('profiles_mode','mode'),
  ('profiles_mode','bio'),
  ('profiles_mode','photos'),
  ('profiles_mode','interests'),
  ('profiles_mode','meta'),
  ('profiles_mode','created_at'),
  ('profiles_mode','updated_at'),
  ('profiles_business','id'),
  ('profiles_business','business_name'),
  ('profiles_business','location'),
  ('profiles_business','area'),
  ('profiles_business','bio'),
  ('profiles_business','tags'),
  ('profiles_business','website'),
  ('profiles_business','instagram'),
  ('profiles_business','facebook'),
  ('profiles_business','linkedin'),
  ('profiles_business','logo_uri'),
  ('profiles_business','created_at'),
  ('profiles_business','updated_at'),
  ('follows','id'),
  ('follows','follower_id'),
  ('follows','followee_id'),
  ('follows','created_at'),
  ('events','id'),
  ('events','created_by'),
  ('events','title'),
  ('events','description'),
  ('events','location'),
  ('events','starts_at'),
  ('events','ends_at'),
  ('events','cover_image_uri'),
  ('events','visibility'),
  ('events','mode'),
  ('events','created_at'),
  ('events','updated_at'),
  ('event_participants','id'),
  ('event_participants','event_id'),
  ('event_participants','user_id'),
  ('event_participants','role'),
  ('event_participants','rsvp_status'),
  ('event_participants','created_at'),
  ('event_invitations','id'),
  ('event_invitations','event_id'),
  ('event_invitations','inviter_id'),
  ('event_invitations','invitee_id'),
  ('event_invitations','status'),
  ('event_invitations','created_at'),
  ('planner_items','id'),
  ('planner_items','created_by'),
  ('planner_items','source_mode'),
  ('planner_items','title'),
  ('planner_items','description'),
  ('planner_items','starts_at'),
  ('planner_items','ends_at'),
  ('planner_items','related_event_id'),
  ('planner_items','related_user_id'),
  ('planner_items','meta'),
  ('planner_items','created_at'),
  ('planner_items','updated_at'),
  ('planner_participants','id'),
  ('planner_participants','planner_item_id'),
  ('planner_participants','user_id'),
  ('planner_participants','role'),
  ('planner_participants','created_at'),
  ('conversations','id'),
  ('conversations','type'),
  ('conversations','mode'),
  ('conversations','created_by'),
  ('conversations','related_event_id'),
  ('conversations','related_group_id'),
  ('conversations','created_at'),
  ('conversations','updated_at'),
  ('conversation_members','id'),
  ('conversation_members','conversation_id'),
  ('conversation_members','user_id'),
  ('conversation_members','role'),
  ('conversation_members','joined_at'),
  ('messages','id'),
  ('messages','conversation_id'),
  ('messages','sender_id'),
  ('messages','content'),
  ('messages','created_at'),
  ('event_chat_settings','id'),
  ('event_chat_settings','event_id'),
  ('event_chat_settings','chat_enabled'),
  ('event_chat_settings','created_at'),
  ('groups','id'),
  ('groups','created_by'),
  ('groups','name'),
  ('groups','mode'),
  ('groups','created_at'),
  ('groups','updated_at'),
  ('group_members','id'),
  ('group_members','group_id'),
  ('group_members','user_id'),
  ('group_members','role'),
  ('group_members','joined_at'),
  ('wishlist_items','id'),
  ('wishlist_items','user_id'),
  ('wishlist_items','title'),
  ('wishlist_items','description'),
  ('wishlist_items','mode'),
  ('wishlist_items','created_at'),
  ('wishlist_items','updated_at'),
  ('user_preferences','id'),
  ('user_preferences','user_id'),
  ('user_preferences','key'),
  ('user_preferences','value'),
  ('user_preferences','created_at'),
  ('user_preferences','updated_at'),
  ('calendar_connections','id'),
  ('calendar_connections','user_id'),
  ('calendar_connections','provider'),
  ('calendar_connections','external_id'),
  ('calendar_connections','token_encrypted'),
  ('calendar_connections','last_sync_at'),
  ('calendar_connections','created_at'),
  ('ai_requests','id'),
  ('ai_requests','user_id'),
  ('ai_requests','mode'),
  ('ai_requests','task'),
  ('ai_requests','created_at')
)
select e.table_name, e.column_name as missing_column
from expected e
left join information_schema.columns c
  on c.table_schema = 'public'
 and c.table_name   = e.table_name
 and c.column_name  = e.column_name
where c.column_name is null
order by e.table_name, e.column_name;
