// apps/mobile/components/ai/AIDisclosureNote.tsx
// EU AI Act (Art. 50) transparency: tell people the concierge is an AI system,
// shown where the concierge first appears. Copy is the line drafted in
// docs/PRIVACY_AND_DSA_DRAFTS.md §4.

import React from "react";
import { View, Text, StyleSheet, type StyleProp, type ViewStyle } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useAppTheme } from "@/constants/design-system";

export const AI_DISCLOSURE_TEXT =
  "Winkly's suggestions are generated by AI and may be imperfect — always use your own judgement, especially for safety.";

/** One-line, low-emphasis AI disclosure for the top of a concierge entry screen. */
export function AIDisclosureNote({ style }: { style?: StyleProp<ViewStyle> }) {
  const theme = useAppTheme();

  return (
    <View
      style={[
        styles.wrap,
        {
          backgroundColor: theme.colors.backgroundMuted,
          borderRadius: theme.radii.md,
          paddingHorizontal: theme.spacing.md,
          paddingVertical: theme.spacing.sm,
          gap: theme.spacing.sm,
        },
        style,
      ]}
    >
      <Ionicons
        name="information-circle-outline"
        size={16}
        color={theme.colors.textSecondary}
        style={styles.icon}
      />
      <Text style={[theme.type.caption, { color: theme.colors.textSecondary, flex: 1, lineHeight: 17 }]}>
        {AI_DISCLOSURE_TEXT}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  icon: { marginTop: 1 },
});
