-- ─────────────────────────────────────────────────────────────────────────────
-- Winkly — Weekly Spark core schema
-- v1.0 – June 2026
-- ─────────────────────────────────────────────────────────────────────────────
-- The weekly ritual: each active user gets up to 3 fresh, ready-to-go plans per
-- week (SOLO / DATE / MEETUP), generated by the `weekly-spark-cron` Edge Function
-- and shown at the top of the Planner. Every venue is verified against Google
-- Places before it is persisted (see `verified_places`, the shared verification
-- cache) — the AI only selects + writes the personalized reason, never venue facts.
--
-- The slot is the future home of paid placements, so the sponsorship rails
-- (`spark_sponsors`, `weekly_spark_plans.sponsored/sponsor_id/source='sponsored'`)
-- exist now but ship OFF (gated by SPARK_SPONSORED_ENABLED in the cron / app).
--
-- RLS: a user can read only their own sparks. The reference caches
-- (`verified_places`, `spark_sponsors`) are readable by any authenticated user
-- (no per-user data); all writes happen via the service role (cron), which
-- bypasses RLS.
--
-- Reversible — DOWN (run manually to undo):
--   DROP TABLE IF EXISTS public.weekly_spark_plans CASCADE;
--   DROP TABLE IF EXISTS public.weekly_sparks CASCADE;
--   DROP TABLE IF EXISTS public.spark_sponsors CASCADE;
--   DROP TABLE IF EXISTS public.verified_places CASCADE;
--   DROP TYPE  IF EXISTS public.spark_slot;
--   DROP TYPE  IF EXISTS public.spark_source;
--   DROP TYPE  IF EXISTS public.spark_sponsor_type;
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Enums ────────────────────────────────────────────────────────────────────
DO $$ BEGIN
  CREATE TYPE spark_slot AS ENUM ('solo', 'date', 'meetup');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE spark_source AS ENUM ('ai', 'winkly_event', 'sponsored');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE spark_sponsor_type AS ENUM ('venue', 'event_org', 'partner');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── verified_places — shared venue verification cache (NO per-user data) ──────
-- Verify a place once via Google Places (Text Search → Place Details), cache it,
-- and reuse for every user/plan within the TTL window (recommend 7 days for the
-- volatile fields business_status + opening_hours). Source of truth for the
-- cron's validation gate AND ai-gateway grounding (single Places integration).
CREATE TABLE IF NOT EXISTS public.verified_places (
  place_id          TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  formatted_address TEXT,
  lat               DOUBLE PRECISION,
  lng               DOUBLE PRECISION,
  business_status   TEXT,
  opening_hours     JSONB,
  website           TEXT,
  google_maps_url   TEXT,
  price_level       INT,
  last_verified_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  source            TEXT NOT NULL DEFAULT 'google_places',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.verified_places IS
  'Shared Google Places verification cache (no per-user data). resolveVerifiedPlace reads/writes this; the volatile fields (business_status, opening_hours) are re-verified lazily once the row is older than the TTL (~7 days).';

CREATE INDEX IF NOT EXISTS verified_places_last_verified_at
  ON public.verified_places (last_verified_at);

-- ── spark_sponsors — sponsorship rails (unused at launch) ─────────────────────
CREATE TABLE IF NOT EXISTS public.spark_sponsors (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name             TEXT NOT NULL,
  type             spark_sponsor_type NOT NULL DEFAULT 'partner',
  disclosure_label TEXT NOT NULL,
  active           BOOLEAN NOT NULL DEFAULT false,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.spark_sponsors IS
  'Rails for future paid placements. A sponsored plan renders disclosure_label ("Partner pick"). Disabled at launch via SPARK_SPONSORED_ENABLED; never bypasses the quality/verification gate.';

-- ── weekly_sparks — one row per user per week ─────────────────────────────────
CREATE TABLE IF NOT EXISTS public.weekly_sparks (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  seen_at    TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  UNIQUE (user_id, week_start)
);

COMMENT ON TABLE public.weekly_sparks IS
  'One Weekly Spark per user per ISO-week (week_start = Monday). seen_at clears the Planner-tab unseen badge. expires_at hides stale sparks.';

CREATE INDEX IF NOT EXISTS weekly_sparks_user_week
  ON public.weekly_sparks (user_id, week_start DESC);

-- ── weekly_spark_plans — up to 3 plans per spark (solo/date/meetup) ───────────
CREATE TABLE IF NOT EXISTS public.weekly_spark_plans (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  spark_id          UUID NOT NULL REFERENCES public.weekly_sparks(id) ON DELETE CASCADE,
  slot              spark_slot NOT NULL,
  rank              INT NOT NULL DEFAULT 0,
  title             TEXT NOT NULL,
  fit_reason        TEXT NOT NULL,
  -- place_id is a real FK into the verification cache so the validation gate's
  -- "resolved place_id" guarantee is enforced at the DB level (null for event slots).
  place_id          TEXT REFERENCES public.verified_places(place_id) ON DELETE SET NULL,
  place_name        TEXT,
  place_lat         DOUBLE PRECISION,
  place_lng         DOUBLE PRECISION,
  starts_at         TIMESTAMPTZ,
  ends_at           TIMESTAMPTZ,
  approx_price_cents INT,
  currency          TEXT,
  booking_url       TEXT,
  source            spark_source NOT NULL DEFAULT 'ai',
  sponsored         BOOLEAN NOT NULL DEFAULT false,
  sponsor_id        UUID REFERENCES public.spark_sponsors(id) ON DELETE SET NULL,
  external_ref      TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (spark_id, slot)
);

COMMENT ON TABLE public.weekly_spark_plans IS
  'A single verified Spark plan for one slot. Venue facts (place_name/lat/lng, hours, price, booking_url) come from verified_places / get-nearby-external-events — never the model. booking_url stays null unless Places verified it.';

CREATE INDEX IF NOT EXISTS weekly_spark_plans_spark ON public.weekly_spark_plans (spark_id);

-- ── RLS ───────────────────────────────────────────────────────────────────────
ALTER TABLE public.verified_places     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spark_sponsors      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_sparks       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_spark_plans  ENABLE ROW LEVEL SECURITY;

-- verified_places: shared reference, readable by any authenticated user. Writes
-- are service-role only (no policy → blocked for authenticated even with grants).
DROP POLICY IF EXISTS verified_places_select ON public.verified_places;
CREATE POLICY verified_places_select ON public.verified_places
  FOR SELECT TO authenticated USING (true);

-- spark_sponsors: disclosure labels readable by any authenticated user.
DROP POLICY IF EXISTS spark_sponsors_select ON public.spark_sponsors;
CREATE POLICY spark_sponsors_select ON public.spark_sponsors
  FOR SELECT TO authenticated USING (true);

-- weekly_sparks: a user reads only their own; they may UPDATE only to mark seen
-- (column-level grant below restricts UPDATE to seen_at). Inserts are cron-only.
DROP POLICY IF EXISTS weekly_sparks_select ON public.weekly_sparks;
CREATE POLICY weekly_sparks_select ON public.weekly_sparks
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS weekly_sparks_update_seen ON public.weekly_sparks;
CREATE POLICY weekly_sparks_update_seen ON public.weekly_sparks
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- weekly_spark_plans: readable only when the parent spark belongs to the caller.
DROP POLICY IF EXISTS weekly_spark_plans_select ON public.weekly_spark_plans;
CREATE POLICY weekly_spark_plans_select ON public.weekly_spark_plans
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.weekly_sparks s
      WHERE s.id = weekly_spark_plans.spark_id
        AND s.user_id = auth.uid()
    )
  );

-- ── Grants ────────────────────────────────────────────────────────────────────
GRANT SELECT ON public.verified_places    TO authenticated;
GRANT SELECT ON public.spark_sponsors     TO authenticated;
GRANT SELECT ON public.weekly_sparks      TO authenticated;
-- Only seen_at is user-writable; the RLS policy still scopes it to the owner.
GRANT UPDATE (seen_at) ON public.weekly_sparks TO authenticated;
GRANT SELECT ON public.weekly_spark_plans TO authenticated;

-- Ensure users.status exists on drifted DBs (original schema defines it, but older
-- environments created via CREATE TABLE IF NOT EXISTS may lack the column).
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';

-- ─────────────────────────────────────────────────────────────────────────────
-- weekly_spark_active_users — service-role batch reader for the cron.
-- Returns one row per ACTIVE user (users.status='active') who can be planned for
-- (has a city OR a stored location), with their privacy-coarsened coordinates and
-- the personalization signals the cron needs. PostGIS stays in SQL (ST_Y/ST_X);
-- the geog point is already coarsened to the user's chosen precision on write.
-- SECURITY DEFINER + service-role-only; never exposed to clients.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.weekly_spark_active_users(p_limit INT, p_offset INT)
RETURNS TABLE (
  user_id              UUID,
  city                 TEXT,
  lat                  DOUBLE PRECISION,
  lng                  DOUBLE PRECISION,
  languages            TEXT[],
  interests            TEXT[],
  activity_preferences TEXT[],
  birthday             DATE,
  modes                TEXT[]
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
  SELECT
    pc.id,
    pc.city,
    ST_Y(ul.geog::geometry) AS lat,
    ST_X(ul.geog::geometry) AS lng,
    pc.languages,
    pc.interests,
    pc.activity_preferences,
    pc.birthday,
    m.modes
  FROM public.profiles_core pc
  JOIN public.users u ON u.id = pc.id AND u.status = 'active'
  LEFT JOIN public.user_locations ul ON ul.user_id = pc.id
  LEFT JOIN LATERAL (
    SELECT array_agg(DISTINCT pm.mode::text) AS modes
    FROM public.profiles_mode pm
    WHERE pm.user_id = pc.id
  ) m ON true
  WHERE (pc.city IS NOT NULL AND length(btrim(pc.city)) > 0) OR ul.user_id IS NOT NULL
  ORDER BY pc.id
  LIMIT GREATEST(p_limit, 0) OFFSET GREATEST(p_offset, 0);
$$;

REVOKE ALL ON FUNCTION public.weekly_spark_active_users(INT, INT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.weekly_spark_active_users(INT, INT) TO service_role;
